services:
  - type: web
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.x.x # замените на версию Python, которую вы используете
    source: .
    startCommand: "python app.py"
    disk:
      name: web
      mountPath: /
